@echo off
set JAVA_OUT=target\generated\proto\java
set GRPC_OUT=target\generated\grpc\java
set SOURCE=src\main\proto
set GEN_DIR=%PROTOC_HOME%\protoc-gen-grpc-java-1.8.0-windows-x86_64.exe

if not exist %JAVA_OUT% mkdir %JAVA_OUT%
if not exist %GRPC_OUT% mkdir %GRPC_OUT%
for /r %SOURCE% %%I in (*.proto) do (
    protoc --java_out=%JAVA_OUT% %SOURCE%\%%~nxI
    protoc --plugin=protoc-gen-grpc-java=%GEN_DIR% --grpc-java_out=%GRPC_OUT% %SOURCE%\%%~nxI
    echo generated by %%~nxI
)
